services:
  django:
    build: .
    ports:
      - 80:8000
    volumes:
      - .:/opt/app
    env_file:
      - .env
  postgres:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db

volumes:
  postgres-data: