# Generated by Django 4.1.7 on 2023-03-15 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_boardingrecord_boarding_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardingrecord',
            name='checkout_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
