# Generated by Django 4.1.7 on 2023-03-15 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_boardingrecord_checkout_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='hourly_rate',
            field=models.FloatField(null=True),
        ),
    ]
